---
# root interfaces
switches:
  br-int:                   # internal switch
    ifname: br-int
    type: static
    address: 192.168.88.1
    netmask: 255.255.255.0
  br-ex:                    # external switch
    ifname: br-ex
    type: static
    address: 0.0.0.0
    netmask: 255.255.255.0
    ports:
     - ifname: ens192
namespaces:
  - name: demo
    interfaces:
    - ifname: einf0         # vNIC in namespce 
      type: static
      address: 0.0.0.0
      bridge:
        ifname: br0
        type: static
        address: 192.168.88.91
        netmask: 255.255.255.0
    - ifname: einf1
      type: static
      address: 0.0.0.0
      bridge:
        ifname: br1
        type: static
        address: 169.254.0.1
        netmask: 255.255.255.0
      pair: no
